CC = cc
FLAGS = -lm

all:CAP2 Restriction count findall varpos lsadt sho_helix Zuk_to_gen

CAP2: CAP2.c
	$(CC) CAP2.c -O -o CAP2
Restriction: Restriction.c
	$(CC) Restriction.c -O -o Restriction
Zuk_to_gen: Zuk_to_gen.c
	$(CC) Zuk_to_gen.c -O -o Zuk_to_gen
count: count.c
	$(CC) count.c -O -o count $(FLAGS)
findall: findall.c
	$(CC) findall.c -O -o findall
lsadt: lsadt.c
	$(CC) lsadt.c -O -o lsadt $(FLAGS)
sho_helix: sho_helix.c
	$(CC) sho_helix.c -O -o sho_helix
varpos: varpos.c
	$(CC) varpos.c -O -o varpos
